@extends('layouts.app')
@section('title', 'Help & Setup')
@section('content')
<section class="panel help-panel"><h2>Your delivery workflow</h2><ol><li><strong>Upload Deliveries:</strong> Select up to ten JPG, PNG or WEBP photos. Use one complete receipt per photo.</li><li><strong>Review Deliveries:</strong> Open a photo. The reader generates text and fills Reference ID, Branch, SKU and Item. Confirm actual received quantities, correct unclear values, then save or approve.</li><li><strong>Approve:</strong> Check the quantities against the photo, then approve the delivery.</li><li><strong>Export:</strong> Copy the table into Google Sheets or download a CSV. Only approved records appear.</li></ol><p>To correct a completed delivery, open it from Completed. Saving for review removes it from exports until approved again.</p><h2>Laravel Herd setup</h2><p>Place this project inside your Herd folder. From the project terminal, run:</p><pre>composer install
copy .env.example .env
php artisan key:generate
php artisan migrate
npm install
npm run build</pre><p>The copy command above is for Windows Command Prompt. In PowerShell use <code>Copy-Item .env.example .env</code>; on macOS use <code>cp .env.example .env</code>. Keep your existing .env if you already configured the project.</p><p>Use PHP 8.4 or later in Herd. The default database is SQLite; create an empty <code>database/database.sqlite</code> if it does not exist. Then open <code>http://htdeliveries.test</code>.</p><h2>Pending integrations</h2><p>Google Sheets syncing is the next phase. The free Tesseract.js reader works in your browser without API keys or paid credits. The OCR engine and English language files are included in this project. Upload your photo, choose its orientation and click Read DR Photo. Use General text mode if Receipt table mode gives poor results.</p><p>Review the generated text and fields carefully. Stamps, handwriting and table columns may be misread or missed. For receipts with a Received Order column, quantities are left blank for you to confirm. Edit the generated text or item rows, then save or approve. Copy Text and Download Text remain available.</p><p>Previously saved readings reopen without rescanning. Check Replace the current editable fields before applying a fresh reading to a saved draft. Cancel reading stops the browser worker.</p><p>This version is for your local Herd workspace and has no login. Add authentication before hosting it online.</p></section>
@endsection
