@extends('layouts.app')
@section('title', 'Review Delivery')
@section('content')
<div class="toolbar"><a class="text-link" href="{{ route('deliveries.index') }}">← Review queue</a><span class="badge {{ $delivery->status }}">{{ $delivery->status === 'completed' ? 'Completed' : 'For review' }}</span></div>
<div class="notice">Check the generated text against the photo. Blank received quantities must be confirmed before approval.</div>
<script type="application/json" id="saved-reading">@json(json_decode($delivery->reading_result ?? 'null', true))</script>
<details class="reader-disclosure"><summary><span><strong>Photo reader</strong><small>Read again, adjust orientation or view extracted text</small></span><span>Settings ▾</span></summary><section class="panel reader-panel" id="receipt-reader" data-url="{{ route('deliveries.read', $delivery->id) }}" data-photo="{{ route('deliveries.photo', $delivery->id) }}" data-worker="{{ asset('ocr/worker.min.js') }}" data-core="{{ asset('ocr/core') }}" data-language="{{ asset('ocr/lang') }}" data-csrf="{{ csrf_token() }}" data-auto="{{ $delivery->status === 'review' && !$delivery->items && !$errors->any() ? '1' : '0' }}" data-editable="{{ !$delivery->items && !$errors->any() ? '1' : '0' }}">
    <div class="panel-heading"><h2>Read photo → Text</h2><button type="button" class="button" id="read-photo" {{ $delivery->status === 'completed' ? 'disabled' : '' }}>Read DR Photo</button></div>
    <p class="subtle">Free OCR runs in your browser. No API key or credits needed.</p>
    <div class="ocr-controls"><label>Photo orientation<select id="ocr-rotation"><option value="auto">Auto portrait</option><option value="0">As uploaded</option><option value="-90">Rotate left 90°</option><option value="90">Rotate right 90°</option><option value="180">Upside down</option></select></label><label>Reading mode<select id="ocr-mode"><option value="6">Receipt table</option><option value="3" selected>General text</option></select></label><button type="button" class="button secondary" id="cancel-reading" disabled>Cancel reading</button></div><progress id="ocr-progress" max="100" value="0" aria-label="Photo reading progress"></progress>
    <p id="reader-status" role="status" aria-live="polite">@if($delivery->reading_result) Previous reading saved. The saved text is below. @else Ready to read. @endif</p>
    <ul id="reader-warnings" class="reader-warnings">@foreach(data_get(json_decode($delivery->reading_result ?? 'null', true), 'warnings', []) as $warning)<li>{{ $warning }}</li>@endforeach</ul>
    <details><summary>Generated receipt text — editable</summary><textarea id="receipt-text" name="raw_text" form="review-form" aria-label="Generated receipt text" placeholder="The photo text will appear here.">{{ data_get(json_decode($delivery->reading_result ?? 'null', true), 'raw_text', '') }}</textarea><button type="button" class="button secondary" id="copy-receipt-text">Copy text</button><button type="button" class="button secondary" id="download-receipt-text">Download text</button><button type="button" class="button secondary" id="save-receipt-text" {{ $delivery->status === 'completed' ? 'disabled' : '' }}>Save text</button><button type="button" class="button secondary" id="parse-receipt-text">Fill fields from edited text</button></details>
    <label class="reader-option"><input type="checkbox" id="replace-reading"> Replace the current editable fields with the reading</label>
    <button type="button" class="text-link" id="read-again" {{ $delivery->status === 'completed' ? 'disabled' : '' }}>Read again (free)</button>
</section></details>
<div class="review-grid"><section class="panel photo-panel"><div class="panel-heading"><h2>Receipt photo</h2><a class="text-link" href="{{ route('deliveries.photo', $delivery->id) }}" target="_blank" rel="noopener">Enlarge ↗</a></div><div class="photo-tools"><button type="button" class="button secondary" id="photo-zoom-out" aria-label="Zoom out">−</button><span id="photo-zoom-label">Fit</span><button type="button" class="button secondary" id="photo-zoom-in" aria-label="Zoom in">+</button><button type="button" class="button secondary" id="photo-fit">Fit photo</button></div><div class="photo-viewport"><img class="receipt-image" src="{{ route('deliveries.photo', $delivery->id) }}" alt="Delivery receipt {{ $delivery->original_name }}"><canvas id="ocr-preview" class="receipt-image" hidden></canvas></div><p class="photo-filename" title="{{ $delivery->original_name }}">{{ $delivery->original_name }}</p></section>
<section class="panel review-details"><div class="panel-heading"><h2>Review items</h2><span class="pill">DR #{{ $delivery->id }}</span></div>
<form method="POST" action="{{ route('deliveries.update', $delivery->id) }}" id="review-form">@csrf @method('PUT')
<div class="field-grid"><label>Reference ID<input name="reference_id" value="{{ old('reference_id', $delivery->reference_id) }}" placeholder="e.g. DR-00125" required maxlength="255"></label><label>Branch<input name="branch" value="{{ old('branch', $delivery->branch) }}" placeholder="e.g. Tabunok" required maxlength="255"></label></div>
<p class="subtle">Compare each row with the photo. Click any field to correct it before approval.</p>
<div class="table-wrap review-items" tabindex="0" aria-label="Scrollable delivery items"><table class="editable-table"><thead><tr><th>No.</th><th>FS Item</th><th>Item SKU</th><th>Item Quantity</th><th>Total Order</th><th>Received Order</th><th></th></tr></thead><tbody id="item-rows">
@foreach(old('items', $delivery->items ?: [['sku' => '', 'item' => '', 'quantity' => '']]) as $index => $item)
<tr><td><input type="text" name="items[{{ $index }}][line_number]" value="{{ $item['line_number'] ?? ($index + 1) }}" aria-label="No." maxlength="255"></td><td><input type="text" name="items[{{ $index }}][item]" value="{{ $item['item'] ?? '' }}" aria-label="FS Item" maxlength="255" required></td><td><input type="text" name="items[{{ $index }}][sku]" value="{{ $item['sku'] ?? '' }}" aria-label="Item SKU" maxlength="255"></td><td><input type="number" name="items[{{ $index }}][item_quantity]" value="{{ $item['item_quantity'] ?? $item['ordered_quantity'] ?? '' }}" aria-label="Item Quantity" step="any" min="0" max="99999999"></td><td><input type="text" name="items[{{ $index }}][total_order]" value="{{ $item['total_order'] ?? '' }}" aria-label="Total Order" maxlength="255"></td><td><input type="number" name="items[{{ $index }}][quantity]" value="{{ $item['quantity'] ?? '' }}" aria-label="Received Order" step="any" min="0" max="99999999" required></td><td><button type="button" class="remove-row" aria-label="Remove item">×</button></td></tr>
@endforeach
</tbody></table></div><button class="button secondary add-row" type="button" id="add-row">+ Add item</button>
<div class="form-actions"><button class="button secondary" name="action" value="save">Save for Review</button><button class="button" name="action" value="approve">✓ Approve Delivery</button></div></form></section></div>
@endsection
